### ISSUE TITLE
Windows Vista SP2 x86 support?

### ISSUE THREAD

**Issue by Vangelis66** [mangui/firefox-hls#1]
Hello and many thanks for your efforts! 

Is this supposed to work under Vista SP2 x86? 
Latest MS updates (August 2016) successfully installed. 

Firefox version: Nightly-51.0a1.en-US.win32[20160906030431]
xpinstall.signatures.required;false 

I have installed latest version (0.0.2) of the extension from AMO: 

https://addons.mozilla.org/firefox/downloads/file/496627/native_hls-0.0.2-fx.xpi

restarted Nightly (not needed, just to be sure) 
and then pasted on the URLbar the following known to work (audio) playlist: 

http://as-hls-ww-live.akamaized.net/pool_7/live/bbc_radio_two/bbc_radio_two.isml/bbc_radio_two-audio=128000.m3u8

No native playback was observed, instead Nightly offered 
to save the playlist as a .m3u8 file.

If I visit directly http://video-dev.github.io/hls.js/demo/
and then paste on the "Enter custom URL below" input field 
the posted URL (AppleHLS audio stream of BBC Radio 2), 
then the audio starts to play fine in the tab...

Vista SP2 has native decoders that enable (through MSE) 
HTML5 playback of AAC (and H264) ....

Google Chrome (last version to run on VistaSP2 is 50.0.2661.102) 
ships with its own patented decoders; I tested the chrome equivalent 
extension "Native HLS Playback v0.4.5" and on Chrome 50 it 
functions as advertised (the playlist plays inside a tab). 

But my browser of choice is Firefox, so any 
insight on this issue will be greatly appreciated!

TIA

**Comment by Vangelis66** [comment]
Most sadly, this issue hasn't received the slightest of attention for more than a year; this fact alone speaks volumes about the developer 👎 ...

 FWIW, a truly working alternative can be found on AMO [here](https://addons.mozilla.org/el/firefox/addon/native_hls_playback/); it's a webextension, installable on Firefox versions >= 48.0

**Comment by mangui** [comment]
looking at your behaviour, it looks like i was well inspired not replying on this ticket ...
31 vs 1070 contributions in a year, good catch buddy !
I have limited amount of time and cannot handle all tickets
![image](https://user-images.githubusercontent.com/1798553/30754868-4bb1728e-9f79-11e7-8514-e9939164c81f.png)
![image](https://user-images.githubusercontent.com/1798553/30754950-9d5b8ca0-9f79-11e7-9093-d5ed10e5c262.png)

**Comment by Vangelis66** [comment]
Hello Guillaume 

Apologies if you got _that_ offended, but I had to vent some serious frustration in my previous comment, frustration that accumulated during the course of many months... However: 

> looking at your behaviour, it looks like i was well inspired not replying on this ticket ...

AFAICT, there was nothing objectionable in my original post that would "inspire you to not reply"; my language/wording was very civil/polite and after all it was a genuine report/query: 

I had previously been in the [**Review**](https://addons.mozilla.org/el/firefox/addon/native-hls/reviews/) section of the [AMO](https://addons.mozilla.org/el/firefox/addon/native-hls/) page for this extension, where at the time (early Sept 2016) all that was there was two "**Great work**" + "**Awesome**" reports; but the add-on _wasn't working as expected on my setup_, so I had to inquire whether this was due to my specific OS; it was from AMO that I ended up here, as I know the AMO review section is not the place to report issues; I already had a GitHub account, so there you go... 
FWIW, after my issue was submitted, two (recently three) "**not working**" reviews appeared on AMO, this made me realise I was not alone; that and your lack of response all those months made me look for a working alternative in AMO (which I only mentioned to possibly aid others, not vex you personally...). 

> 31 vs 1070 contributions in a year, good catch buddy !

With the greatest of respect, I find that remark (plus accompanying attachments) to be totally out of context/place; yes (unlike you) I'm not a coder, in this context I was/am a mere Firefox user looking for a working extension; however GitHub is not frequented by coders only; ANYONE can create an account here, being able to write code is not a hard requirement (Thank The Lord); in fact, many code-illiterate people join GitHub to report issues for GitHub hosted projects (just like this one)... 
Are you implying I would have been treated differently (as far as my original issue report is concerned) in the event I was a mature coder with hundreds of contributions?

> I have limited amount of time and cannot handle all tickets

... This is totally understandable and fully accepted, but, sadly, this pretty much describes many open source project managers/code authors on GitHub and elsewhere; please try to also look things from a user's perspective, too; I frequent many open source projects and I never exert any type of pressure on their maintainers after a bug is submitted; notice how silent I stayed in this case for almost 12 and a half months; but today I realised I wouldn't be getting any resolution soon, for whatever reasons not tied to me :disappointed:; if your indeed exceptional contributions record limits you severely in addressing issues in this tracker, maybe in the end you should consider disabling this issue tracker altogether via your project settings... 

To conclude, I harbour no ill feelings towards you, despite being (sort of) frowned upon... 
I wish you the best in your coding endeavours 

Regards
